# Tuned PID values for your drone
# Generated by tune_pid_interactive.py

HOVER_THRUST = 4.0712

# Altitude PID
ALT_KP = 21.0
ALT_KI = 0.0
ALT_KD = 0.05

# Attitude PID (roll and pitch)
ATT_KP = 2.5
ATT_KI = 0.2
ATT_KD = 0.8

# Velocity PID (outer loop)
VEL_KP = 0.2
VEL_KI = 0.0
VEL_KD = 0.03
VEL_MAX_ANGLE_DEG = 15.0
